name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    env:
      LANG: zh_CN.UTF-8
      LC_ALL: zh_CN.UTF-8
      POWERSHELL_TELEMETRY_OPTOUT: 1

    steps:
      #- run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      #- run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      #- run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      #- run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      #- run: echo "🖥️ The workflow is now ready to test your code on the runner."
      #- name: List files in the repository
      #  run: |
       #   ls ${{ github.workspace }}
      - name: excute script auto-script-singbox
        run: |
           cd D:\a\autos\autos\ls
            #powershell -ExecutionPolicy Bypass -File .ps1
             powershell -ExecutionPolicy Bypass -File D:\a\autos\autos\ls\AutoMergeUpLoad.ps1
      - name: List files
        run: dir
        shell: cmd
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: generated-json
          path: D:\a\autos\autos\ls\merged_formatted4.json

      - run: echo "🍏 This job's status is ${{ job.status }}."
